# Generated by Django 3.2.7 on 2021-12-09 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('tour_app', '0001_initial'), ('tour_app', '0002_auto_20211201_2226'), ('tour_app', '0003_auto_20211209_1722'), ('tour_app', '0004_remove_profile_zip_ext')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(max_length=100)),
                ('loc_address', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=17, unique=True)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=18, unique=True)),
                ('description', models.TextField()),
                ('operation_hours', models.TimeField()),
                ('pictures', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerary_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=17)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=18)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_app.itinerary')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(default='', max_length=90)),
                ('zipcode', models.CharField(default='00000', max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
