<<<<<<< HEAD
# Generated by Django 3.2.7 on 2021-11-17 20:05
=======
# Generated by Django 3.2.7 on 2021-11-17 00:22
>>>>>>> 059fa4c05764b886c4117b2baf0b46d66fd7ea02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
<<<<<<< HEAD
        ('auth', '0012_alter_user_first_name_max_length'),
=======
>>>>>>> 059fa4c05764b886c4117b2baf0b46d66fd7ea02
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(max_length=100)),
                ('loc_address', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=17, unique=True)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=18, unique=True)),
                ('description', models.TextField()),
                ('operation_hours', models.TimeField()),
                ('pictures', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
<<<<<<< HEAD
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('itinerary_name', models.CharField(max_length=100)),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerary_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> 059fa4c05764b886c4117b2baf0b46d66fd7ea02
            ],
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
<<<<<<< HEAD
=======
        migrations.CreateModel(
            name='Itinerary_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=17)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=18)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_app.itinerary')),
            ],
        ),
>>>>>>> 059fa4c05764b886c4117b2baf0b46d66fd7ea02
    ]
