# Generated by Django 3.2.7 on 2021-12-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0001_squashed_0004_remove_profile_zip_ext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zipcode',
            field=models.CharField(default='', max_length=5),
        ),
    ]
