# Generated by Django 3.2.7 on 2021-12-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='city',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='zip_ext',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='zipcode',
            field=models.CharField(default='00000', max_length=5),
        ),
    ]
